### ISSUE TITLE
OSX Instructions

### ISSUE THREAD

**Issue by Miserlou** [vancluever/docker-nomad#4]
OSX doesn't have `getent`, so it'd be great if there were a note about that for OSX users. I thiiiink I got it working using the staff group but I have a few other steps to get through before I can confirm that, so I'm not really sure.

**Comment by vancluever** [comment]
Hey @Miserlou, the new instructions should (hopefully) be a lot more platform-agnostic as we no longer attempt to do any fancy things inside the container to try and get access to the docker socket. I was noticing in my own troubleshooting that this was not working anyway.

Going to close this due to age (sorry by the way)! If you are still interested and have any issues using the new instructions please let me know.

Thanks!
